from .base import Rule, Severity

JS_RULES: list[Rule] = [
    Rule(
        id="JS001", severity=Severity.CRITICAL,
        title="Use of eval()",
        description="eval() executes arbitrary JavaScript from strings.",
        pattern=r"\beval\s*\(",
        fix="Avoid eval(). Use JSON.parse() for data, proper functions for logic.",
        cwe="CWE-95",
        tags=["injection", "code-execution"],
        extensions=[".js", ".ts", ".mjs", ".cjs"],
    ),
    Rule(
        id="JS002", severity=Severity.HIGH,
        title="innerHTML assignment",
        description="Setting innerHTML with user data leads to XSS.",
        pattern=r"\.innerHTML\s*=",
        fix="Use textContent or DOMPurify to sanitize before innerHTML.",
        cwe="CWE-79",
        tags=["xss", "dom"],
        extensions=[".js", ".ts", ".html"],
    ),
    Rule(
        id="JS003", severity=Severity.HIGH,
        title="document.write() usage",
        description="document.write() with user data enables XSS.",
        pattern=r"document\.write\s*\(",
        fix="Use DOM manipulation methods instead.",
        cwe="CWE-79",
        tags=["xss", "dom"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS004", severity=Severity.MEDIUM,
        title="Hardcoded secret or API key",
        description="Secrets hardcoded in JavaScript are exposed to all users.",
        pattern=r'(apiKey|api_key|secret|password|token)\s*[:=]\s*["\'][^"\']{6,}["\']',
        fix="Use environment variables and never commit secrets to source control.",
        cwe="CWE-798",
        tags=["secrets", "credentials"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS005", severity=Severity.HIGH,
        title="SQL injection via string concatenation",
        description="Building SQL queries with string concatenation allows injection.",
        pattern=r'(query|sql)\s*[+=]\s*[`"\'].*\+',
        fix="Use parameterized queries or an ORM.",
        cwe="CWE-89",
        tags=["sql-injection", "database"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS006", severity=Severity.HIGH,
        title="Command injection via exec/spawn with user input",
        description="Passing user data to child_process functions enables OS injection.",
        pattern=r"(exec|execSync|spawn)\s*\(\s*[`\"'].*\$\{",
        fix="Validate and sanitize all input before shell execution.",
        cwe="CWE-78",
        tags=["command-injection", "os"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS007", severity=Severity.MEDIUM,
        title="Prototype pollution",
        description="Merging objects without key validation enables prototype pollution.",
        pattern=r"__proto__|constructor\[.prototype.\]",
        fix="Validate keys before object merging. Use Object.create(null).",
        cwe="CWE-1321",
        tags=["prototype-pollution"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS008", severity=Severity.LOW,
        title="console.log with sensitive data",
        description="Logging sensitive variables to console leaks data.",
        pattern=r"console\.log\s*\([^)]*?(password|token|secret|key)[^)]*\)",
        fix="Remove or redact sensitive fields before logging.",
        cwe="CWE-532",
        tags=["information-disclosure", "logging"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS009", severity=Severity.HIGH,
        title="Insecure use of Math.random()",
        description="Math.random() is not cryptographically secure.",
        pattern=r"\bMath\.random\s*\(\s*\)",
        fix="Use crypto.getRandomValues() for security-sensitive operations.",
        cwe="CWE-338",
        tags=["crypto", "randomness"],
        extensions=[".js", ".ts"],
    ),
    Rule(
        id="JS010", severity=Severity.MEDIUM,
        title="Open redirect",
        description="Redirecting to user-controlled URLs enables phishing.",
        pattern=r"(res\.redirect|location\.href|location\.replace)\s*\([^)]*req\.",
        fix="Validate redirect target against a whitelist of allowed URLs.",
        cwe="CWE-601",
        tags=["redirect", "phishing"],
        extensions=[".js", ".ts"],
    ),
]
