from .base import Rule, Severity

JAVA_RULES: list[Rule] = [
    Rule(
        id="JV001", severity=Severity.CRITICAL,
        title="SQL injection via string concatenation",
        description="Building SQL with string concatenation enables injection.",
        pattern=r'(executeQuery|executeUpdate|prepareStatement)\s*\(\s*"[^"]*"\s*\+',
        fix="Use PreparedStatement with parameterized queries.",
        cwe="CWE-89",
        tags=["sql-injection", "database"],
        extensions=[".java", ".kt"],
    ),
    Rule(
        id="JV002", severity=Severity.CRITICAL,
        title="Deserialization of untrusted data (ObjectInputStream)",
        description="Java deserialization of untrusted data allows RCE.",
        pattern=r"\bObjectInputStream\b",
        fix="Avoid Java serialization. Use JSON/XML with schema validation.",
        cwe="CWE-502",
        tags=["deserialization", "rce"],
        extensions=[".java"],
    ),
    Rule(
        id="JV003", severity=Severity.HIGH,
        title="Command injection via Runtime.exec()",
        description="Passing user data to Runtime.exec() enables OS command injection.",
        pattern=r"Runtime\.getRuntime\(\)\.exec\s*\(",
        fix="Use ProcessBuilder with argument lists, never shell strings.",
        cwe="CWE-78",
        tags=["command-injection", "os"],
        extensions=[".java"],
    ),
    Rule(
        id="JV004", severity=Severity.HIGH,
        title="Path traversal via user input",
        description="Building file paths from user input allows directory traversal.",
        pattern=r"new\s+File\s*\([^)]*request\.(getParameter|getAttribute)",
        fix="Validate and canonicalize paths. Use Path.toRealPath().",
        cwe="CWE-22",
        tags=["path-traversal", "file"],
        extensions=[".java"],
    ),
    Rule(
        id="JV005", severity=Severity.HIGH,
        title="Use of MD5 or SHA1",
        description="MD5 and SHA1 are cryptographically broken.",
        pattern=r'MessageDigest\.getInstance\s*\(\s*"(MD5|SHA-1|SHA1)"',
        fix='Use MessageDigest.getInstance("SHA-256") or better.',
        cwe="CWE-327",
        tags=["crypto", "hashing"],
        extensions=[".java"],
    ),
    Rule(
        id="JV006", severity=Severity.MEDIUM,
        title="Hardcoded password or secret",
        description="Hardcoded credentials are exposed in source code.",
        pattern=r'(password|secret|apiKey|api_key)\s*=\s*"[^"]{4,}"',
        fix="Use environment variables or a vault.",
        cwe="CWE-798",
        tags=["secrets", "credentials"],
        extensions=[".java", ".kt"],
    ),
    Rule(
        id="JV007", severity=Severity.MEDIUM,
        title="Insecure random (java.util.Random)",
        description="java.util.Random is not cryptographically secure.",
        pattern=r"\bnew\s+Random\s*\(",
        fix="Use java.security.SecureRandom for security-sensitive operations.",
        cwe="CWE-338",
        tags=["crypto", "randomness"],
        extensions=[".java"],
    ),
    Rule(
        id="JV008", severity=Severity.HIGH,
        title="XSS via PrintWriter output",
        description="Writing user input directly to HTTP response enables XSS.",
        pattern=r"(out|response)\.(println|print|write)\s*\([^)]*request\.getParameter",
        fix="Encode output with OWASP Java Encoder before writing to response.",
        cwe="CWE-79",
        tags=["xss", "web"],
        extensions=[".java"],
    ),
    Rule(
        id="JV009", severity=Severity.LOW,
        title="Empty catch block",
        description="Swallowing exceptions hides errors and may mask security issues.",
        pattern=r"catch\s*\([^)]+\)\s*\{\s*\}",
        fix="Log or handle exceptions appropriately.",
        cwe="CWE-390",
        tags=["error-handling", "code-quality"],
        extensions=[".java", ".kt"],
    ),
    Rule(
        id="JV010", severity=Severity.MEDIUM,
        title="Kotlin !! (non-null assertion)",
        description="!! throws NullPointerException on null, risking DoS.",
        pattern=r"!!\.",
        fix="Use safe calls (?.) and Elvis operator (?:) instead.",
        cwe="CWE-476",
        tags=["null-dereference", "kotlin"],
        extensions=[".kt"],
    ),
]
