from .base import Rule, Severity

PYTHON_RULES: list[Rule] = [
    Rule(
        id="PY001", severity=Severity.CRITICAL,
        title="Use of eval()",
        description="eval() executes arbitrary Python code from user input.",
        pattern=r"\beval\s*\(",
        fix="Avoid eval(). Use ast.literal_eval() for safe expression parsing.",
        cwe="CWE-95",
        tags=["injection", "code-execution"],
        extensions=[".py"],
    ),
    Rule(
        id="PY002", severity=Severity.CRITICAL,
        title="Use of exec()",
        description="exec() executes arbitrary Python code.",
        pattern=r"\bexec\s*\(",
        fix="Avoid exec(). Refactor to use safe alternatives.",
        cwe="CWE-95",
        tags=["injection", "code-execution"],
        extensions=[".py"],
    ),
    Rule(
        id="PY003", severity=Severity.HIGH,
        title="Use of pickle / unpickle",
        description="Deserializing untrusted pickle data allows arbitrary code execution.",
        pattern=r"\bpickle\.loads?\s*\(|\bcPickle\b",
        fix="Use JSON or another safe serialization format for untrusted data.",
        cwe="CWE-502",
        tags=["deserialization", "injection"],
        extensions=[".py"],
    ),
    Rule(
        id="PY004", severity=Severity.HIGH,
        title="Shell injection via subprocess with shell=True",
        description="subprocess with shell=True and user input enables command injection.",
        pattern=r"subprocess\.(run|call|Popen|check_output)\s*\([^)]*shell\s*=\s*True",
        fix="Use shell=False and pass arguments as a list.",
        cwe="CWE-78",
        tags=["command-injection", "os"],
        extensions=[".py"],
    ),
    Rule(
        id="PY005", severity=Severity.HIGH,
        title="Use of os.system()",
        description="os.system() is vulnerable to command injection.",
        pattern=r"\bos\.system\s*\(",
        fix="Use subprocess with a list of arguments instead.",
        cwe="CWE-78",
        tags=["command-injection", "os"],
        extensions=[".py"],
    ),
    Rule(
        id="PY006", severity=Severity.MEDIUM,
        title="Hardcoded password or secret",
        description="Hardcoded credentials in source code.",
        pattern=r'(password|secret|api_key|token)\s*=\s*["\'][^"\']{4,}["\']',
        fix="Use environment variables or a secrets manager.",
        cwe="CWE-798",
        tags=["secrets", "credentials"],
        extensions=[".py"],
    ),
    Rule(
        id="PY007", severity=Severity.MEDIUM,
        title="Use of MD5 or SHA1 for hashing",
        description="MD5 and SHA1 are cryptographically broken.",
        pattern=r"hashlib\.(md5|sha1)\s*\(",
        fix="Use SHA-256 or better (hashlib.sha256).",
        cwe="CWE-327",
        tags=["crypto", "hashing"],
        extensions=[".py"],
    ),
    Rule(
        id="PY008", severity=Severity.HIGH,
        title="SQL injection via string formatting",
        description="Building SQL queries with string formatting allows injection.",
        pattern=r'(execute|cursor\.execute)\s*\(\s*[f"\'].*%.*["\']|f".*SELECT|f\'.*SELECT',
        fix="Use parameterized queries: cursor.execute(query, (param,))",
        cwe="CWE-89",
        tags=["sql-injection", "database"],
        extensions=[".py"],
    ),
    Rule(
        id="PY009", severity=Severity.LOW,
        title="Use of assert for security checks",
        description="assert statements are removed with -O flag, bypassing checks.",
        pattern=r"\bassert\b.*(auth|permission|admin|role|token)",
        fix="Use explicit if/raise instead of assert for security logic.",
        cwe="CWE-617",
        tags=["logic", "auth"],
        extensions=[".py"],
    ),
    Rule(
        id="PY010", severity=Severity.MEDIUM,
        title="Weak random for security",
        description="random module is not cryptographically secure.",
        pattern=r"\brandom\.(random|randint|choice|shuffle)\s*\(",
        fix="Use secrets module for security-sensitive randomness.",
        cwe="CWE-338",
        tags=["crypto", "randomness"],
        extensions=[".py"],
    ),
]
