from .base import Rule, Severity

RUST_RULES: list[Rule] = [
    Rule(
        id="RS001", severity=Severity.CRITICAL,
        title="Unsafe block usage",
        description="unsafe blocks bypass Rust's memory safety guarantees.",
        pattern=r"\bunsafe\s*\{",
        fix="Minimize unsafe usage. Document invariants and review carefully.",
        cwe="CWE-119",
        tags=["memory", "unsafe"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS002", severity=Severity.HIGH,
        title="unwrap() on Result/Option",
        description="unwrap() panics on None/Err, causing potential DoS.",
        pattern=r"\.(unwrap|expect)\s*\(",
        fix="Use match, if let, or the ? operator for proper error handling.",
        cwe="CWE-390",
        tags=["panic", "error-handling"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS003", severity=Severity.HIGH,
        title="Command injection via Command::new with user input",
        description="Passing user-controlled data to Command enables OS injection.",
        pattern=r"Command::new\s*\([^)]*\b(input|user|arg|param)\b",
        fix="Validate and sanitize all input before passing to Command.",
        cwe="CWE-78",
        tags=["command-injection", "os"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS004", severity=Severity.MEDIUM,
        title="Hardcoded secret or password",
        description="Hardcoded credentials in source code.",
        pattern=r'(password|secret|api_key|token)\s*=\s*"[^"]{4,}"',
        fix="Use environment variables or a secrets manager.",
        cwe="CWE-798",
        tags=["secrets", "credentials"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS005", severity=Severity.MEDIUM,
        title="Use of deprecated/weak crypto (MD5/SHA1)",
        description="MD5 and SHA1 are cryptographically broken.",
        pattern=r"\b(Md5|Sha1|md5|sha1)\b",
        fix="Use SHA-256 or better via the sha2 crate.",
        cwe="CWE-327",
        tags=["crypto", "hashing"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS006", severity=Severity.LOW,
        title="TODO / FIXME in security-sensitive area",
        description="Unresolved TODOs in code may indicate incomplete security logic.",
        pattern=r"//\s*(TODO|FIXME|HACK|XXX)",
        fix="Resolve all TODOs before production deployment.",
        cwe=None,
        tags=["code-quality"],
        extensions=[".rs"],
    ),
    Rule(
        id="RS007", severity=Severity.HIGH,
        title="SQL query built with format!()",
        description="Building SQL queries via format!() enables SQL injection.",
        pattern=r'format!\s*\(\s*"[^"]*SELECT|format!\s*\(\s*"[^"]*INSERT|format!\s*\(\s*"[^"]*DELETE',
        fix="Use parameterized queries via sqlx or diesel.",
        cwe="CWE-89",
        tags=["sql-injection", "database"],
        extensions=[".rs"],
    ),
]
